services:
  frontend:
    build:
      context: ./frontend
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build: 
      context: ./backend
    networks:
      - app-network
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data: