services:
  frontend:
    build:
      context: ./frontend
      target: dependencies
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - "5173:5173"
    environment:
      - VITE_DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - VITE_DISCORD_REDIRECT_URI=https://127.0.0.1:5173/callback
      - VITE_DISCORD_SCOPES=identify
      - VITE_BACKEND_URL=http://localhost:5000/api

  backend:
    ports:
      - "5000:5000"
    environment:
      - SERVER_PORT=5000
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_REDIRECT_URI=https://127.0.0.1:5173/callback
      - FRONTEND_URL=https://127.0.0.1:5173
      - JUDGE0_URL=${JUDGE0_URL}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  postgres:
    ports:
      - "5432:5432"  # Expose PostgreSQL for local development